### ISSUE TITLE
OS hardening

### ISSUE THREAD

**Issue by frite** [grnet/grnet-images#2]
_Possibly on wrong repo, if so, close it and comment the appropriate repo_
Regarding the available images -and not only- I suggest the following:
1. **PermitRootLogin no** _it is yes at the time in certain images (ie Debian)_ 
At least in the images I've seen it is allowed by default. I am pretty sure that most people won't change it which exposes the user and downgrades the infrastructure (ie. an attacker to login as root and do whatever he wants -malware distribution, spamming campaigns etc etc- ).
2. Default password. The size of the password (usually 10 chars long) is small and easily bruteforced. 

Thanks none the less

**Comment by skalkoto** [comment]
Hello,
1) the Debian Base image does not have any other user account than root. We cannot disable ssh for root.
2) This has nothing to do with the images. If the generated password during deployment is not strong enough, this has to do with synnefo.
