### ISSUE TITLE
CoreOS fixed /etc/machine-id content

### ISSUE THREAD

**Issue by vinilios** [grnet/grnet-images#3]
It seems that every vm created using the current CoreOS image shares a common 
`/etc/machine-id` file. The file, which seems to be installed/setup by systemd, 
is supposed to contain a unique identifier for the machine. The shared 
identifier caused me issues setting up an etcd cluster between several ~okeanos 
virtual machines. I was able to overcome this either by deleting the machine-id 
file and rebooting the vm (CoreOS seems to regenerate the file on boot), or 
by injecting my own file during vm creation.

**Comment by skalkoto** [comment]
fixed in coreos-835.12.0-1
